# Generated by Django 5.2.4 on 2025-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eb_gh_cli", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubissue",
            name="is_pr",
            field=models.BooleanField(
                default=False, help_text="Indicates if the issue is a pull request"
            ),
        ),
    ]
