# Generated by Django 5.2.4 on 2025-07-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eb_gh_cli", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubissue",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, help_text="Issue number in the repository", null=True
            ),
        ),
        migrations.AlterField(
            model_name="githubpullrequest",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, help_text="Pull request number in the repository", null=True
            ),
        ),
        migrations.AlterField(
            model_name="githubuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="githubissue",
            unique_together={("repository", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="githubpullrequest",
            unique_together={("repository", "number")},
        ),
    ]
