# Generated by Django 5.2.4 on 2025-07-11 09:06

import django.db.models.deletion
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eb_gh_cli", "0002_alter_githubissue_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubPRFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gh_id",
                    models.BigIntegerField(
                        help_text="GitHub ID of the object", null=True, unique=True
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
                ("internal_created_at", models.DateTimeField(auto_now_add=True)),
                ("internal_updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=512)),
                (
                    "prev_name",
                    models.CharField(
                        blank=True,
                        help_text="Previous name of the file if renamed",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("sha", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("added", "Added"),
                            ("removed", "Removed"),
                            ("modified", "Modified"),
                            ("renamed", "Renamed"),
                            ("copied", "Copied"),
                            ("changed", "Changed"),
                            ("unchanged", "Unchanged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("additions", models.PositiveIntegerField(default=0)),
                ("deletions", models.PositiveIntegerField(default=0)),
                ("changes", models.PositiveIntegerField(default=0)),
                ("blob_url", models.URLField(max_length=512)),
                ("raw_url", models.URLField(max_length=512)),
                ("contents_url", models.URLField(max_length=512)),
                (
                    "patch",
                    models.TextField(
                        blank=True, help_text="Patch for the file changes", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="GithubGist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gh_id",
                    models.BigIntegerField(
                        help_text="GitHub ID of the object", null=True, unique=True
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
                ("internal_created_at", models.DateTimeField(auto_now_add=True)),
                ("internal_updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("public", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gists",
                        to="eb_gh_cli.githubuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="GithubGistFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gh_id",
                    models.BigIntegerField(
                        help_text="GitHub ID of the object", null=True, unique=True
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
                ("internal_created_at", models.DateTimeField(auto_now_add=True)),
                ("internal_updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=512)),
                ("language", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_url", models.URLField(max_length=512)),
                ("size", models.PositiveIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Type of the file (e.g., text/plain)",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.FileField(
                        blank=True,
                        help_text="Content of the file",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "gist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="eb_gh_cli.githubgist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model,),
        ),
    ]
