# Generated by Django 5.2.4 on 2025-07-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eb_gh_cli', '0003_githubgist_githubgistfile_githubprfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubprfile',
            name='sha',
            field=models.CharField(blank=True, help_text='SHA of the file from github', max_length=40, null=True),
        ),
    ]
