# Generated by Django 5.2.4 on 2025-07-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eb_gh_cli", "0004_alter_githubprfile_sha"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GithubPRFile",
            new_name="GithubFile",
        ),
    ]
