# Generated by Django 5.2.4 on 2025-07-17 13:22

import typing

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eb_gh_cli", "0005_rename_githubprfile_githubfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gh_id",
                    models.BigIntegerField(
                        help_text="GitHub ID of the object", null=True, unique=True
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
                ("internal_created_at", models.DateTimeField(auto_now_add=True)),
                ("internal_updated_at", models.DateTimeField(auto_now=True)),
                ("sha", models.CharField(max_length=40, unique=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "last_modified",
                    models.DateTimeField(help_text="Last modified time of the commit"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_commits",
                        to="eb_gh_cli.githubuser",
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Parent commits of this commit",
                        related_name="child_commits",
                        to="eb_gh_cli.githubcommit",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="eb_gh_cli.githubrepository",
                    ),
                ),
            ],
            options={
                "unique_together": {("repository", "sha")},
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name="githubfile",
            name="commit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="eb_gh_cli.githubcommit",
            ),
        ),
        migrations.AddField(
            model_name="githubpullrequest",
            name="commits",
            field=models.ManyToManyField(
                blank=True,
                help_text="Commits associated with this pull request",
                related_name="pull_requests",
                to="eb_gh_cli.githubcommit",
            ),
        ),
    ]
