# Generated by Django 5.2.4 on 2025-08-04 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eb_gh_cli", "0006_githubcommit_githubfile_commit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubgist",
            name="gist_id",
            field=models.CharField(
                default=0,
                help_text="Unique identifier for the Gist",
                max_length=128,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="githubgist",
            name="source_comment",
            field=models.ForeignKey(
                blank=True,
                help_text="Comment from which this Gist was extracted, if any",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gists",
                to="eb_gh_cli.githubissuecomment",
            ),
        ),
        migrations.AddField(
            model_name="githubgist",
            name="source_gist",
            field=models.ForeignKey(
                blank=True,
                help_text="Gist from which this Gist was extracted, if any",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gists",
                to="eb_gh_cli.githubgist",
            ),
        ),
        migrations.AddField(
            model_name="githubgist",
            name="source_issue",
            field=models.ForeignKey(
                blank=True,
                help_text="Issue from which this Gist was extracted, if any",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gists",
                to="eb_gh_cli.githubissue",
            ),
        ),
    ]
