# Generated by Django 5.2.4 on 2025-08-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eb_gh_cli", "0007_githubgist_gist_id_githubgist_source_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubgist",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="githubgist",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
