# Generated by Django 5.2.4 on 2025-08-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eb_gh_cli", "0008_alter_githubgist_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubcommit",
            name="sha",
            field=models.CharField(max_length=40),
        ),
    ]
