# Generated by Django 5.2.4 on 2025-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eb_gh_cli", "0009_alter_githubcommit_sha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubprreview",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
