# Generated by Django 5.2.4 on 2025-10-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eb_gh_cli", "0011_githubprreview_deleted_alter_githubcommit_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubissuecomment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
